# Generated by Django 4.1.2 on 2023-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img1',
            field=models.ImageField(null=True, upload_to='house_pics'),
        ),
    ]
