# Generated by Django 4.1.2 on 2023-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0002_house_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img2',
            field=models.ImageField(null=True, upload_to='house_pics'),
        ),
        migrations.AddField(
            model_name='house',
            name='img3',
            field=models.ImageField(null=True, upload_to='house_pics'),
        ),
    ]
