# Generated by Django 4.1.2 on 2023-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0003_house_img2_house_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
                ('reppass', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264)),
                ('x', models.IntegerField()),
            ],
        ),
    ]
