# Generated by Django 4.1.2 on 2023-08-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0006_house_houseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='houseid',
        ),
    ]
